### ISSUE TITLE
viewport mode shows a zoomed UI

### ISSUE THREAD

**Issue by xpqzl** [jhlothamer/audio_node_wrangler_addon#1]
Hi! Thank you for your addon! I'm using the window size of my game in 480x270 and scaling to a window size of 1920x1080 and using the strech mode set to "viewport" generate a pixelated render. When I call the plugin pressing F1 the UI shows zoomed.
![Uploading audiowrangler error.png…]()

**Comment by jhlothamer** [comment]
Thanks for bringing this issue to my attentions!

The UI was not created with a pixel art game in mind.  I'll figure out something that will work in such a small viewport. Probably a different UI option.  I'll let you know when I've fixed it on this issue.  Should be by this weekend.

**Comment by jhlothamer** [comment]
@xpqzl  I added a new branch called pixel_art_ui with what I hope will be a fix.  With this change a different UI will be used when you hit F1 while running your game.  It has all the same features but changes the filter and command button layout.  Would you be willing to download the code from this repo and try it out?  I want to know what you think of my choice of font sizes.

To download and try the fix just switch from the main branch to pixel_game_ui and then click the Code button which brings up a dialog where you can click download zip.

To be sure you've got the newer version, please check that the plugin version you see in Godot's project settings is 4.1.1.

**Comment by xpqzl** [comment]
Hi @jhlothamer ! I'll try today and send you the feedback. Thank you so much <3

**Comment by jhlothamer** [comment]
I merged the pixel art UI changes into the main branch and have updated the asset library entry for the add-on.  The asset library edit should be approved in a day or so.

I added instructions on how to modify the font sizes for the pixel art UI (also refered to as the mini UI) in the readme.  Of course you can modify anything else you want as well.  But I hope what I've done works out of the box for you.
